### ISSUE TITLE
Levantar contato de possíveis locais para realização do evento

### ISSUE THREAD

**Issue by naanadr** [pyladiesrecife/organizacao#11]
#### Por que essa atividade é importante?
Precisamos entrar em contato com possíveis locais para realizar o evento, mas antes de entrar em contato precisamos levantar esses contatos.

#### O que é esperado que seja entregue com essa atividade?
Os contatos podem ser pessoas responsáveis, e-mail, telefone. Responder essa issue com o contato das pessoas.

#### Quem pode pegar essa atividade?
Qualquer pessoa e mais de uma pessoa pode estar fazendo essa mesma atividade. Quem for pegando ela para fazer, por favor responda a issue informando para que todes fiquem a par do status.

### Referencias
- [Explicação e sugestões de locais para realizar o evento](https://github.com/okfn-brasil/embaixadoras/blob/main/Guia-ODD/ODD2023.md#4-onde-realizar-meu-evento)
- Mais informações sobre o evento, ver o [Guia ODD 2023](https://github.com/okfn-brasil/embaixadoras/blob/main/Guia-ODD/ODD2023.md) e a [Página oficial do evento](https://opendataday.org/pt_br/)

### Notas
- Precisamos ter confirmação do local até o dia 22 de fevereiro, para [concorrer a bolsa de ajuda de custo](https://github.com/okfn-brasil/embaixadoras/blob/main/Guia-ODD/ODD2023.md#8-precisa-se-inscrever-em-algum-lugar-para-organizar-um-odd). Caso não temos a confirmação de algum lugar, podemos se inscrever e adicionar sugestões de locais. Porque imagino que muitos locais não retornarão o nosso contato a tempo.

**Comment by naanadr** [comment]
Em mente em tenho os seguintes contatos:

1. Departamento de computação da UFRPE
  - diretoria.dc[at]ufrpe.br
  - secretaria.dc[at]ufrpe.br
2. Coordenação do curso de Ciência da Computação da UFRPE
  - coordenacao.bcc[at]ufrpe.br
  - secretaria.bcc[at]ufrpe.br
4. CESAR School 
  - Estou em um grupo com as professoras do CESAR School

**Comment by naanadr** [comment]
@cecivieira tu tem ideia de mais locais que poderíamos tentar contato?

**Comment by tiidadavena** [comment]
Email enviado para a [FICR](https://ficr.catolica.edu.br/portal/) no dia 27/02.

**Comment by naanadr** [comment]
Evento vai ser realizado no escritório da TW
