### ISSUE TITLE
Entrar em contato com possíveis locais para realizar o evento

### ISSUE THREAD

**Issue by naanadr** [pyladiesrecife/organizacao#12]
#### Por que essa atividade é importante?
Precisamos entrar em contato com possíveis locais para realizar o evento e se possível **ter a confirmação deles até o dia 22 de fevereiro**.

#### O que é esperado que seja entregue com essa atividade?
Levantamento das características do local, como:
- Qual a capacidade?
- Possui local para montar coffe break?
- Oferece datashow e internet?
- Irão oferecer algum apoio?
- Querem algo em troca?
- Quanto será a locação do local?
- Tem disponibilidade para receber o evento entre os dias 04 e 10 e março de 2023?

#### Quem pode pegar essa atividade?
Qualquer pessoa e mais de uma pessoa pode estar fazendo essa mesma atividade. Quem for pegando ela para fazer, por favor responda a issue informando para que todes fiquem a par do status. 

### Referencias
- [Explicação e sugestões de locais para realizar o evento](https://github.com/okfn-brasil/embaixadoras/blob/main/Guia-ODD/ODD2023.md#4-onde-realizar-meu-evento)
- Mais informações sobre o evento, ver o [Guia ODD 2023](https://github.com/okfn-brasil/embaixadoras/blob/main/Guia-ODD/ODD2023.md) e a [Página oficial do evento](https://opendataday.org/pt_br/)

### Notas
- Precisamos ter confirmação do local até o dia 22 de fevereiro, para [concorrer a bolsa de ajuda de custo](https://github.com/okfn-brasil/embaixadoras/blob/main/Guia-ODD/ODD2023.md#8-precisa-se-inscrever-em-algum-lugar-para-organizar-um-odd). Caso não temos a confirmação de algum lugar, podemos se inscrever e adicionar sugestões de locais. Porque imagino que muitos locais não retornarão o nosso contato a tempo.

**Comment by naanadr** [comment]
Aguardando desenvolvimento da Issue #11 , para que tenhamos os contatos dos locais.

**Comment by naanadr** [comment]
### Retornos ate o momento

#### Apolo 235

Entrei em contato por telefone e por e-mail com o SENAC, mas o contato por telefone teve um retorno mais rápido. Me informaram que o auditório está em reforma e deve ser entregue no final de março 😢 

### Aguardando retorno

#### UFPRE / Departamento de Computação

Enviei e-mail para a secretaria do departamento e estou aguardando retorno

#### CESAR School

As professoras do CESAR perguntaram melhor sobre o evento e informaram que a unica data possível seria dia 04 de março 😢 
Ficaram de confirmar com a secretaria se haveria disponibilidade nesse dia.

**Comment by anicelysantos** [comment]
Gente, pensei em alguns lugares quando estava pensando no Cerveja com Dados. Não sei se a estrutura dessas sugestões abraça os pré requisitos ditos lá em cima, mas segue:

- Che Bar e Comedoria
- Dunajeun (@dunajeun) - um bar novo que abriu ali pela boa vista
- Empório Barrozo

Pensando em espaços mais formais:
- UNICAP
- FG da Boa Vista
- Uninassau das Graças

Eu não tenho nenhum desses contatos, só estava pensando em lugares mesmo.

**Comment by naanadr** [comment]
@luanamirandaa ficou de entrar em contato com o pessoal da TW Recife para verificar disponibilidade em realizar o evento no dia 11/03 no turno da manhã

**Comment by anicelysantos** [comment]
Tô vendo com Otacílio como consegue o escritório do iFood. Eles organizaram um hacktober ano passado lá.

**Comment by luanamirandaa** [comment]
Oi gente!

Já mandei a solicitação pra TW. Vai rolar lá

Em qui., 2 de mar. de 2023 09:05, Anicely Santos ***@***.***>
escreveu:

**Comment by naanadr** [comment]
Evento vai ser realizado na TW
