### ISSUE TITLE
 [Reunião] Planejamento Sprint Hacktoberfest

### ISSUE THREAD

**Issue by cecivieira** [pyladiesrecife/organizacao#2]
# Planejamento Sprint Hacktoberfest

- Data: 26 set. 2022
- Participantes:

Nome e sobrenome | @GitHub ou e-mail (opcional) | 
--| --|
Maria Fernanda Souza| --|
Ana Cecília Vieira | --|
Anicely Santos | --|
Keila Viana | --|

### Itens a serem debatidos

- [x] Contexto dos anos anteriores
- [x] Estrutura:
    - Oficina Git/Github com mão na massa na sexta-feira (07) as 19h - facilitadoras Fernanda e Keila
    - Apresentação das ferramentas que o site tá construído, distribui issues e sprint no sábado (08) 
- [x] Auxílio transporte
    - Será fornecida passagem de transporte público para participantes que solicitarem. É obrigatória a participação na oficina da sexta, como monitora ou participante.
- [x] Ferramentas
    - Git
    - VS Code
- [x] No formulário coletar:
    - Nome
    - RG/CPF
    - Gênero
    - Restrição alimentar
    - Necessidade de notebook
    - Necessidade de auxílio transporte
    - Código do VEM
    - Termo de responsabilidade de recarga do VEM

### Ações para serem realizadas

Atividade| Responsável | Link útil|
 --| --| --|
Fazer arte| --| --|
Fazer formulário | --| --|
Inserir todas as presentes no grupo de whatsapp das prof. do CESAR| --| --|
Criar novas issues| --| --|

**Comment by naanadr** [comment]
Adicionando aqui informações que coletamos até o momento

- CESAR SCHOOL irá oferecer coffee break. As professoras pediram para que até segunda-feira, confirmamos a quantidade. Mas ela ficaram de ver se podemos confirmar mais próximo do evento.
- Na sala reservada possuem 30 cadeiras, para caso vá mais pessoas elas irão reservar a sala ao lado. Mesmo que algumas pessoas levem computadores, a sala possue 30 locais para sentar. 


Tópicos finalizados
- [ X ] Arte de divulgação
- [ X ] Texto de divulgação
- [ X ] Formulário de inscrição 
- [ X ] PyLadies no grupo do whatsapp 

Precisa ser feito 
- [ ] Revisar as issues
- [ ] Atualizar o linktree com a URL do formulário 
- [ ] Divulgar formulário de inscrição
- [ ] Planejar oficina de Git/GitHub

Seria interessante fazer
- [ ] Arte auxiliar de divulgação. Porque iremos ter quase 7 dias para preencher o formulário. Poderíamos ter uma arte extra.

**Comment by naanadr** [comment]
Adicionando aqui informações que coletamos até o momento

- CESAR SCHOOL irá oferecer coffee break. As professoras pediram para que até segunda-feira, confirmamos a quantidade. Mas ela ficaram de ver se podemos confirmar mais próximo do evento.
- Na sala reservada possuem 30 cadeiras, para caso vá mais pessoas elas irão reservar a sala ao lado. Mesmo que algumas pessoas levem computadores, a sala possue 30 locais para sentar. 


Tópicos finalizados
- [ X ] Arte de divulgação
- [ X ] Texto de divulgação
- [ X ] Formulário de inscrição 
- [ X ] PyLadies no grupo do whatsapp 

Precisa ser feito 
- [ ] Revisar as issues
- [ ] Atualizar o linktree com a URL do formulário 
- [ ] Divulgar formulário de inscrição
- [ ] Planejar oficina de Git/GitHub

Seria interessante fazer
- [ ] Arte auxiliar de divulgação. Porque iremos ter quase 7 dias para preencher o formulário. Poderíamos ter uma arte extra.


**Pontos que não ficaram claros para mim**
- Iremos recarregar o VEM apenas no dia do evento? 
Porque pensei em explicar isso no formulário, mas fiquei na dúvida se era isso mesmo.

**Comment by cecivieira** [comment]
@naanadr vamos carregar o vem de quem aparecer na oficina do github, no dia anterior.
Acho que foi isso que decidimos
