### ISSUE TITLE
Entrar contato com outras comunidades PyLadies 

### ISSUE THREAD

**Issue by cecivieira** [pyladiesrecife/organizacao#9]
Entrar em contato com outras comunidades PyLadies para saber se existe plano de patrocínio existente.

**Comment by emidiafelipe** [comment]
Conseguiu avançar, @cecivieira? Precisa de ajuda?

**Comment by cecivieira** [comment]
@emidiafelipe enviei mensagem para os outros cap[itulos e estou aguardando resposta

**Comment by cecivieira** [comment]
PyLadies Fortaleza - Plano de patrocínio 
https://drive.google.com/file/d/1jdKkP4klxCgfkdvJPHjT000SU_Xh_kKA/view?usp=share_link

**Comment by cecivieira** [comment]
PyLadies Paraíba - Plano de patrocínio
https://drive.google.com/file/d/1VCk9xbTuH8nZnJvzR0NSJjgY0wppkkU3/view?usp=share_link

**Comment by emidiafelipe** [comment]
Muito massa, @cecivieira! A gente consegue o ppt original pra aproveitar o layout?

**Comment by cecivieira** [comment]
Tô verificando
